# Generated by Django 5.1.5 on 2025-02-26 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentimentTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text_tl', models.TextField(blank=True, null=True)),
                ('question_text_en', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('options', models.JSONField(blank=True, default=list, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentimentResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('sentiment', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('words', models.JSONField(blank=True, default=list, null=True)),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_results', to='feedbacks.feedback')),
                ('sentiment_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_results', to='sentiment_tests.sentimenttest')),
            ],
            options={
                'unique_together': {('sentiment_test', 'feedback', 'mode')},
            },
        ),
    ]
