# Generated by Django 5.1.5 on 2025-01-26 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentresult',
            name='sentiment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='sentiment_magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='sentiment_test',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_results', to='sentiment_tests.sentimenttest'),
        ),
    ]
