# Generated by Django 5.1.5 on 2025-01-26 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_remove_feedback_sentiment_result'),
        ('sentiment_tests', '0002_sentimentresult_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentresult',
            name='feedback',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_results', to='feedbacks.feedback'),
        ),
    ]
