# Generated by Django 5.1.5 on 2025-01-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_tests', '0003_sentimentresult_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentimentresult',
            old_name='sentiment_magnitude',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='sentimentresult',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='sentimentresult',
            name='sentiment_score',
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='emotion_detected',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='negative_words',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='positive_words',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='sentimenttest',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sentimenttest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sentimenttest',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
