# Generated by Django 5.1.5 on 2025-02-01 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_feedbackcollection_remove_feedback_user_nid'),
        ('sentiment_tests', '0004_rename_sentiment_magnitude_sentimentresult_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sentimenttest',
            old_name='question_text',
            new_name='description',
        ),
        migrations.AlterUniqueTogether(
            name='sentimentresult',
            unique_together={('sentiment_test', 'feedback')},
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='detailed_results',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='sentimenttest',
            name='options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='sentimenttest',
            name='question_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimenttest',
            name='question_text_tl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimenttest',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentresult',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_results', to='feedbacks.feedback'),
        ),
        migrations.AlterField(
            model_name='sentimentresult',
            name='sentiment_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_results', to='sentiment_tests.sentimenttest'),
        ),
        migrations.RemoveField(
            model_name='sentimentresult',
            name='emotion_detected',
        ),
    ]
