# Generated by Django 5.1.5 on 2025-02-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_tests', '0005_sentimentcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimenttest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
