# Generated by Django 5.1.5 on 2025-02-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_feedbackcollection_remove_feedback_user_nid'),
        ('sentiment_tests', '0007_rename_detailed_results_sentimentresult_details_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sentimentresult',
            unique_together={('sentiment_test', 'feedback', 'mode')},
        ),
    ]
