# Generated by Django 5.1.5 on 2025-02-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
