# Generated by Django 5.1.5 on 2025-01-28 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('age_detected', models.IntegerField()),
                ('gender_detected', models.CharField(max_length=10)),
                ('emotion_detected', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
