# Generated by Django 5.1.5 on 2025-02-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='services',
            field=models.ManyToManyField(related_name='employees', to='dashboard.service'),
        ),
    ]
