# Generated by Django 5.1.5 on 2025-02-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0002_alter_employeeinfo_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='employeeinfo', to='dashboard.service'),
        ),
    ]
