# Generated by Django 5.1.5 on 2025-02-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_service_image_service_image_url'),
        ('users', '0002_employeeinfo_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='employees', to='dashboard.service'),
        ),
    ]
