# Generated by Django 5.1.5 on 2025-01-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
