# Generated by Django 5.1.5 on 2025-02-26 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_service_created_at_alter_service_image_url'),
        ('feedbacks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employeeinfo', to='users.employeeinfo'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='dashboard.service'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seniorcitizeninfo', to='users.seniorcitizeninfo'),
        ),
    ]
