# Generated by Django 5.1.5 on 2025-01-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_feedback_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_nid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
