# Generated by Django 5.1.5 on 2025-02-01 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_remove_feedback_sentiment_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_nid', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_nid',
        ),
    ]
