# Generated by Django 5.1.5 on 2025-02-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_feedbackcollection_remove_feedback_user_nid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackCollection',
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_nid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
